language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
before_script:
  - composer install --dev
  - composer update satooshi/php-coveralls --dev
script:
    - ant coverage
after_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v -c .coveralls.yml; fi;'
